### ISSUE TITLE
installing

### ISSUE THREAD

**Issue by c0ffymachyne** [alsa-project/libhitaki#6]
how do I install this library ? I have tried but it pretty much gets stuck on hinawa saying "error: there is nothing to install in `hitaki-sys v0.3.0`, because it has no binaries"

**Comment by takaswie** [comment]
> how do I install this library ? I have tried but it pretty much gets stuck on hinawa saying "error: there is nothing to install in `hitaki-sys v0.3.0`, because it has no binaries"

Thanks for the question. I think you tried to build the other software, I guess it is [snd-firewire-ctl-services](https://github.com/alsa-project/snd-firewire-ctl-services). If so, yes, it depends on some C libraries even if it is written by Rust language. The dependent libraries are:

 - [libhinawa](https://github.com/alsa-project/libhinawa)
 - [libhitaki](https://github.com/alsa-project/libhitaki)
 - libraries provided by [alsa-gobject](https://github.com/alsa-project/alsa-gobject/)

Libhitaki is one of them. When installing, please refer and follow to README. When
finding any unclear point, please inform it to me with command examples.

Thanks

**Comment by takaswie** [comment]
Let me close the issue because of no reactions during almost half a year.
